abbr -a rl 'source ~/.config/fish/config.fish'
abbr -a ef 'nvim ~/projects/dot-files/fish/config.fish'
abbr -a effn 'nvim ~/.config/fish/functions/'
# Git abbreviations
abbr -a gf 'git fetch -p'
abbr -a gc 'git commit'
abbr -a gst 'git status'
abbr -a gm 'git merge'
abbr -a gma 'git stash; git checkout master;'
abbr -a gco 'git checkout'
abbr -a gbr 'git checkout -b'
abbr -a gp 'git stash pop'
abbr -a gdc 'git checkout -- .'
abbr -a grm 'git rebase master -i'
abbr -a gs 'git status'
abbr -a gbk 'git checkout -'
abbr -a gbp 'git checkout -; git pop'
abbr -g gl 'git log --oneline'
abbr -a e 'nvim'
abbr -a kgp 'kubectl get pods'
abbr -a wkgp 'watch kubectl get pods'
abbr -a kd 'kubectl describe'
abbr -a ke 'kubectl exec -it'
abbr -a klg 'kubectl logs'
abbr -a kdc 'kubectl describe'
abbr -a ev 'nvim ~/projects/dot-files/nvim/init.vim'
abbr -a etm 'nvim ~/projects/dot-files/tmux/.tmux.conf'

abbr -a prn 'pr --action=nvim'
abbr -a prs 'pr --action=subl'
abbr -a prc 'pr --action=vscode'
abbr -a prp 'pr --action=phpstorm'
abbr -a prij 'pr --action=ij'
